### ISSUE TITLE
AttributeError: 'module' object has no attribute 'FullLoader'

### ISSUE THREAD

**Issue by ybdong919** [CDCgov/NCHHSTP-DTBE-Varpipe-WGS#1]
**What type of help do you need?**

* [ ] Question

**Please describe how you'd like us to help.**
$ ./runVarpipeline.sh
ls: cannot access *_L001_R2_001*: No such file or directory
ls: cannot access *_L001_R1_001*: No such file or directory
rm: cannot remove ‘*_L00*’: No such file or directory

../tools/Varpipeline -q A01_R1_001.fastq.gz -r ../tools/ref2.fa -n A01 -q2 A01_R2_001.fastq.gz -a -v

Traceback (most recent call last):
  File "../tools/Varpipeline", line 97, in <module>
    args.verbose, ' '.join(sys.argv))
  File "/blue/bphl-florida/dongyibo/CDC_TB_pipeline/NCHHSTP-DTBE-Varpipe-WGS/tools/Varpipeline.py", line 76, in __init__
    cfg       = yaml.load(ymlfile, Loader=yaml.FullLoader)
AttributeError: 'module' object has no attribute 'FullLoader'
../tools/Varpipeline -q A04_R1_001.fastq.gz -r ../tools/ref2.fa -n A04 -q2 A04_R2_001.fastq.gz -a -v

Traceback (most recent call last):
  File "../tools/Varpipeline", line 97, in <module>
    args.verbose, ' '.join(sys.argv))
  File "/blue/bphl-florida/dongyibo/CDC_TB_pipeline/NCHHSTP-DTBE-Varpipe-WGS/tools/Varpipeline.py", line 76, in __init__
    cfg       = yaml.load(ymlfile, Loader=yaml.FullLoader)
AttributeError: 'module' object has no attribute 'FullLoader'
../tools/Varpipeline -q A06_R1_001.fastq.gz -r ../tools/ref2.fa -n A06 -q2 A06_R2_001.fastq.gz -a -v

Traceback (most recent call last):
  File "../tools/Varpipeline", line 97, in <module>
    args.verbose, ' '.join(sys.argv))
  File "/blue/bphl-florida/dongyibo/CDC_TB_pipeline/NCHHSTP-DTBE-Varpipe-WGS/tools/Varpipeline.py", line 76, in __init__
    cfg       = yaml.load(ymlfile, Loader=yaml.FullLoader)
AttributeError: 'module' object has no attribute 'FullLoader'

**Comment by reagank** [comment]
This should be resolved with the most recent commit - d396209
